version: '3.9'

volumes:
  cache:
    driver: local
  database:
    driver: local

services:
  cache:
    image: redis
    command: redis-server --save 60 1 --loglevel warning --port ${REDIS_PORT} # --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - cache:/data

  database:
    image: postgres:13
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - database:/data
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
      PGPORT: '${DB_PORT}'

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    depends_on:
      - database
    environment:
      DATABASE_URL: 'postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable'
    volumes:
      - ./:/app
    entrypoint:
      - bash
      - -c
    command:
      - dbmate wait && dbmate up && ([ -d "db/seeds" ] && dbmate --migrations-dir=db/seeds --migrations-table=seed_migrations up || true)

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    depends_on:
      - cache
      - database
      - migrations
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
